### ISSUE TITLE
Release 1.0.0 stable api

### ISSUE THREAD

**Issue by glensc** [perftools/php-profiler#15]
- [x] make collector configurable, currently, the user can't pick a specific one: https://github.com/perftools/php-profiler/pull/18
- [x] make saver configurable. <del>currently, the user can't pick a specific one</del>
- [x] add token to upload saver: https://github.com/perftools/php-profiler/pull/17
- [x] make pdo, mongodb dependencies optional
- [ ] <del>detach from xhgui-collector package</del>

**Comment by glensc** [comment]
@markstory here's my vision.

prior 1.0.0 release can make breaking change with any minor version. after that need to bump major version to make breaking changes. so I'd like all design changes be done before 1.0.0 release.

**Comment by glensc** [comment]
> - [ ] detach from xhgui-collector package, make pdo, mongodb dependencies optional

this point would mean needing to copy logic from xhggui-collector package here, but at this point must mark xhgui-collector package abandoned, not to support two codebase doing basically the same.

but then there's xhgui main application, that needs the saver classes. in my mind I would support only HTTP based submitting, then the saver classes can stay internal to xhgui application. this should be 
 maybe 2.0.0 goal for php-profiler?

design wise it makes things easier to maintain and able to provide backward compatibility (php-profiler could submit version key and xhgui application can adjust accordingly if the data format changes). and setting up profiling in the application seems also easier if you don't need to set up MongoDB or pdo connection from the application, just URL with a token. firewall wise, it makes no difference does the application needs access to database connection or HTTP, you still need to access via network xhgui application to submit data.

x-ref:
- https://github.com/perftools/xhgui/pull/273#issuecomment-646243892
- https://github.com/perftools/xhgui/pull/230
- https://github.com/perftools/xhgui-collector/pull/5

**Comment by markstory** [comment]
Having to configure the storage layer in both the 'collector' and 'xhgui application' has long bothered me. It would be much nicer if the collector library could submit runs to a 'storage handler' via local sockets or HTTP and then not have the collecting application need to know about how/where run data is being stored. This would help with your goals of making the collector and saver configurable.

> design wise it makes things easier to maintain and able to provide backward compatibility (php-profiler could submit version key and xhgui application can adjust accordingly if the data format changes). and setting up profiling in the application seems also easier if you don't need to set up MongoDB or pdo connection from the application, just URL with a token. firewall wise, it makes no difference does the application needs access to database connection or HTTP, you still need to access via network xhgui application to submit data.

Totally agree here. Directly inserting into mongo from the collecting application was a bad idea in hindsight

**Comment by glensc** [comment]
Looks like specifying saver was possible already, added PR that documents and unifies the config structure: https://github.com/perftools/php-profiler/pull/16

**Comment by glensc** [comment]
perhaps the `enable()`/`disable()` should always work, i.e not depend on `profiler.enable`?

so that you can just profile code-points in your applications, i.e the advanced usage:
- https://github.com/perftools/php-profiler#advanced-usage

and make ease of unit testing (no hidden dependencies):
- https://github.com/perftools/php-profiler/pull/30

and the `profiler.enable` would be used for auto-mode:
- https://github.com/perftools/php-profiler#create-profiler


```php
    $profiler = new \Xhgui\Profiler\Profiler($config);

    // The profiler itself checks whether it should be enabled
    // for request (executes lambda function from config)
    $profiler->start();

    // shutdown handler collects and stores the data.
    $profiler->registerShutdownHandler();
```

and I wonder is the separate `registerShutdownHandler` call needed? move that logic to `start` method?

cc @perftools/maintainers

**Comment by glensc** [comment]
and I wonder is the separate `registerShutdownHandler` call needed? move that logic to "start" method?

**Comment by markstory** [comment]
I think having explicit enable/disable methods makes sense. It gives users more control on when and what is collected.

**Comment by glensc** [comment]
Alright, here it is: https://github.com/perftools/php-profiler/pull/34

**Comment by glensc** [comment]
the goals marked here are accomplished.

altho I'm hesitant to release 1.0.0 stable yet.

seems the library is used only by me right now :)
