### ISSUE TITLE
Set ProfilingId from Profiler?

### ISSUE THREAD

**Issue by glensc** [perftools/php-profiler#39]
In mongo saver there's getLastProfilingId method:
- https://github.com/perftools/xhgui-collector/blob/1.8.1/src/Xhgui/Saver/Mongo.php#L41-L50

that has a side-effect, that if this saver is called in the application side, the id would be re-used for multiple profilings.

I don't know if that's deliberate or not, but using other savers this functionality is not present.

Question:
- should the id be generated on the profiler side or xhgui side?

Having it profiler side could overwrite (accidentally or deliberately) existing profiling. I don't think saving the same id twice will merge the results?

Having it set at the profiler side, allows the profiler to control the id value.

and if reading the importer section:
- https://github.com/perftools/xhgui#profiling-a-web-request-or-cli-script

it says importing the same profile twice creates duplicate profiling, so the duplicate id sent from profiler is not overwriting other profilers? is there any point then having value re-used? set from profiler?

cc @perftools/maintainers

**Comment by glensc** [comment]
Considering this issue:
- https://github.com/perftools/xhgui/issues/274

I think there should be no way for the profiler (saver) to specify _id, i.e every submit should be accepted as new profiling submit.

**Comment by glensc** [comment]
Unit tests in xhgui assume the `_id` can be set by fixture, and therefore the tests fail because PDO driver doesn't allow it:

```
1) XHGui\Test\Controller\RunTest::testCallgraph
Exception: No profile data found.
```

- https://travis-ci.org/github/perftools/xhgui/jobs/730020468

**Comment by glensc** [comment]
Allow id-override in pdo saver:
- https://github.com/perftools/xhgui/pull/339

similarly in mongo saver:
- https://github.com/perftools/xhgui-collector/pull/11

but the override is there just to allow testing, at least for pdo.

**Comment by markstory** [comment]
It would be simpler if the clients didn't generate ids. That would allow the server and each storage implementation to generate the appropriate ID as required. It also prevents duplicate IDs from being created.

**Comment by glensc** [comment]
thanks, @markstory I've come to the same conclusion, just haven't got around to implementing it so.

**Comment by glensc** [comment]
also, the import method should return the id in the response:
- https://github.com/perftools/xhgui/pull/345

**Comment by glensc** [comment]
ignoring Id from saver if one is provided:
- https://github.com/perftools/xhgui/pull/348

**Comment by glensc** [comment]
Providing id from profiler is no longer supported with latest xhgui (it's ignored).

**Comment by glensc** [comment]
The getLastProfilingId() was added in:
- https://github.com/perftools/xhgui-collector/pull/2

it was a mistake and is removed by now.

a better approach, if need to identify requests and profilers, is to use UNIQUE_ID in env:
- https://github.com/perftools/php-profiler/pull/55
