### ISSUE TITLE
invalid document for insert: keys cannot contain "."

### ISSUE THREAD

**Issue by zengmm** [perftools/php-profiler#60]
PHP Fatal error:  Uncaught MongoDB\Driver\Exception\InvalidArgumentException: invalid document for insert: keys cannot contain "."
/vendor/mongodb/mongodb/src/Operation/InsertOne.php:103

**Comment by glensc** [comment]
this is fixed in xhgui 0.16:
- https://github.com/perftools/xhgui/pull/352

what version of xhgui you are using? please include versions of your bug report!

**Comment by zengmm** [comment]
I refer to https://github.com/perftools/php-profiler#installation and https://github.com/perftools/php-profiler#mongodb-saver

**Comment by glensc** [comment]
Use upload saver:
- https://github.com/perftools/php-profiler#upload-saver

or if direct access to xhgui not possible, use file saver:
- https://github.com/perftools/php-profiler#file-saver

**Comment by glensc** [comment]
However, duplicated the fix in this project as well, for now:
- https://github.com/perftools/php-profiler/pull/61
