### ISSUE TITLE
Change default branch to `main`

### ISSUE THREAD

**Issue by glensc** [perftools/php-profiler#65]
The reason is simple, I've already used to switching to branch `main`.

This will give also out impression to other developers that the project is modern and actively maintained ;)

**Comment by glensc** [comment]
@markstory looks like I don't have enough mana to make the changes. can you bump my privileges in this project?

**Comment by markstory** [comment]
@glensc You should have admin on this repo now. You may have gotten a notification about a repository removal, but you will still have access via the `maintainers` team.

**Comment by glensc** [comment]
changed target branch of all open pull requests to `main`. changed base branch to `main`.

**Comment by glensc** [comment]
@markstory notification of repository removal? huh? what repository was removed?
