### ISSUE TITLE
Support php 8.1.* version inside composer.json

### ISSUE THREAD

**Issue by msidorenko** [perftools/php-profiler#66]
Can you add support for 8.1 version into your composer.json, please ?

Currently composer.json locked for 
`"php": "^5.3.0 || ^7.0 || ^8.0"`

**Comment by glensc** [comment]
why don't you send a pull request?

**Comment by glensc** [comment]
what is the problem? "^8.0" covers ">=8.0 && <9.0":
- https://getcomposer.org/doc/articles/versions.md#caret-version-range-

**Comment by msidorenko** [comment]
Sorry, it was my fault
