### ISSUE TITLE
ArrayAcces implementation PHP 8.1 Compatibility

### ISSUE THREAD

**Issue by Quazz** [perftools/php-profiler#76]
Currently https://github.com/perftools/php-profiler/blob/main/src/Config.php will throw deprecation notices because any implementation of ArrayAccess needs to have the methods compatible.

`PHP Deprecated:  Return type of Xhgui\Profiler\Config::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice`

as an example, but all the offset functions are affected.

So as it says; either the return type must be defined or it must be noted that the return type will change

**Comment by glensc** [comment]
Pull requests are accepted

**Comment by glensc** [comment]
🚧 Never link to branches, share a permalink 🚧
- see https://news.ycombinator.com/item?id=8046710
  and https://help.github.com/articles/getting-permanent-links-to-files/
  and https://docs.gitlab.com/ee/user/shortcuts.html#project-files
- hit `y`
- and perhaps for https://github.com/josephfrazier/octopermalinker (GitHub)

**Comment by glensc** [comment]
Permalink for posterity as the reported has not edited their post:
- https://github.com/perftools/php-profiler/blob/main@%7B2022-06-09T09:50:42Z%7D/src/Config.php
